import type { DayType } from '../types';

// Full labels for workout page
export const dayTypeLabels: Record<DayType, string> = {
  squat_emphasis: 'LOWER — Squat Emphasis',
  bench_emphasis: 'UPPER — Bench Emphasis',
  deadlift_emphasis: 'LOWER — Deadlift Emphasis',
  bench_volume: 'UPPER — Bench Volume',
  arms_shoulders: 'MINI — Arms & Shoulders',
  fb_strength: 'FULL BODY — Strength Focus',
  fb_continued_a: 'FULL BODY — Continued',
  fb_hypertrophy: 'FULL BODY — Hypertrophy Focus',
  fb_continued_b: 'FULL BODY — Continued',
  arms_hypertrophy: 'ARM & HYPERTROPHY DAY',
  lower_body: 'LOWER BODY — Focus',
  upper_body: 'UPPER BODY — Focus',
  lower_body_continued: 'LOWER BODY — Continued',
  upper_body_continued: 'UPPER BODY — Continued',
  vb_squat_force: 'D4 — AGACHO PRIMÁRIO + VOLUME DE SUPINO + OMBRO E BRAÇO',
  vb_bench_force: 'D2 — FORÇA DE SUPINO + PRÁTICA DE TERRA',
  vb_squat_volume: 'D3 — AGACHO HIGH BAR SECUNDÁRIO + PRÁTICA DE SUPINO',
  vb_deadlift_force: 'D5 — FORÇA DE TERRA + HINGE + ESTÉTICA',
  vb_squat_tertiary: 'D1 — AGACHO TERCIÁRIO (PAUSA) + VOLUME DE SUPINO',
  vb_taper: 'TAPER — SESSÃO LEVE',
  vb_mock_meet: 'SIMULADO — 3 TENTATIVAS POR LEVANTAMENTO',
};

// Short labels for dashboard
export const dayTypeShortLabels: Record<DayType, string> = {
  squat_emphasis: 'LOWER — Squat',
  bench_emphasis: 'UPPER — Bench',
  deadlift_emphasis: 'LOWER — Deadlift',
  bench_volume: 'UPPER — Volume',
  arms_shoulders: 'MINI — Arms',
  fb_strength: 'FULL — Strength',
  fb_continued_a: 'FULL — Continued',
  fb_hypertrophy: 'FULL — Hypertrophy',
  fb_continued_b: 'FULL — Continued',
  arms_hypertrophy: 'ARMS — Hypertrophy',
  lower_body: 'LOWER — Focus',
  upper_body: 'UPPER — Focus',
  lower_body_continued: 'LOWER — Continued',
  upper_body_continued: 'UPPER — Continued',
  vb_squat_force: 'D4 — Agacho Primário',
  vb_bench_force: 'D2 — Supino Força',
  vb_squat_volume: 'D3 — Agacho Secundário',
  vb_deadlift_force: 'D5 — Terra Força',
  vb_squat_tertiary: 'D1 — Agacho Terciário',
  vb_taper: 'TAPER — Leve',
  vb_mock_meet: 'SIMULADO',
};

// Portuguese labels for calendar
export const dayTypePtLabels: Record<DayType, string> = {
  squat_emphasis: 'Ênfase Agachamento',
  bench_emphasis: 'Ênfase Supino',
  deadlift_emphasis: 'Ênfase Deadlift',
  bench_volume: 'Volume Supino',
  arms_shoulders: 'Braços & Ombros',
  fb_strength: 'Corpo Inteiro — Força',
  fb_continued_a: 'Corpo Inteiro — Continuação',
  fb_hypertrophy: 'Corpo Inteiro — Hipertrofia',
  fb_continued_b: 'Corpo Inteiro — Continuação',
  arms_hypertrophy: 'Braços & Hipertrofia',
  lower_body: 'Inferiores',
  upper_body: 'Superiores',
  lower_body_continued: 'Inferiores — Continuação',
  upper_body_continued: 'Superiores — Continuação',
  vb_squat_force: 'Agacho Primário',
  vb_bench_force: 'Força de Supino',
  vb_squat_volume: 'Agacho Secundário (High Bar)',
  vb_deadlift_force: 'Força de Terra',
  vb_squat_tertiary: 'Agacho Terciário (Pausa)',
  vb_taper: 'Taper — Sessão Leve',
  vb_mock_meet: 'Simulado',
};

/** Sigla de 2-3 letras para grades compactas (Dashboard, Calendar). */
export const dayTypeAbbrev: Record<DayType, string> = {
  squat_emphasis: 'SQT',
  bench_emphasis: 'BNC',
  deadlift_emphasis: 'DLF',
  bench_volume: 'VOL',
  arms_shoulders: 'ARM',
  fb_strength: 'FB1',
  fb_continued_a: 'FB2',
  fb_hypertrophy: 'FB3',
  fb_continued_b: 'FB4',
  arms_hypertrophy: 'ARM',
  lower_body: 'LO1',
  upper_body: 'UP1',
  lower_body_continued: 'LO2',
  upper_body_continued: 'UP2',
  vb_squat_force: 'D4',
  vb_bench_force: 'D2',
  vb_squat_volume: 'D3',
  vb_deadlift_force: 'D5',
  vb_squat_tertiary: 'D1',
  vb_taper: 'TAP',
  vb_mock_meet: 'SIM',
};
