import { writeFileSync } from 'node:fs';

const SOURCE = {
  document: 'IPF Technical Rulebook',
  version: '2026 v3',
  url: 'https://www.powerlifting.sport/fileadmin/ipf/data/rules/technical-rules/english/2026_IPF_Technical_Rulebook__effective_01_March_2026__v3.pdf',
  effective: '2026-03-01',
  pdf: 'research/corpus/ipf/2026_IPF_Technical_Rulebook_v3.pdf',
  text: 'research/corpus/ipf/rulebook-2026.md',
};

// [at, topics, claim, verbatim, params]
const rows = [
  // ---------- AGACHAMENTO: a definição e o procedimento ----------
  ['§4.1.3', ['agacho', 'profundidade', 'regras-ipf'],
    'a profundidade legal do agachamento é definida assim: descer até que a superfície superior das pernas na articulação do quadril esteja mais baixa que o topo dos joelhos',
    'the lifter must bend the knees and lower the body until the top surface of the legs at the hip joint is lower than the top of the knees', []],
  ['§4.1.3', ['agacho', 'tecnica', 'regras-ipf'],
    'só uma tentativa de descida é permitida',
    'Only one descent attempt is allowed', []],
  ['§4.1.3', ['agacho', 'regras-ipf'],
    'a tentativa é considerada iniciada quando os joelhos do atleta destravam',
    'The attempt is deemed to have commenced when the lifters knees have unlocked', []],
  ['§4.1.2', ['agacho', 'comandos-ipf'],
    'o sinal de início do agachamento é um movimento do braço para baixo mais o comando audível squat',
    'The signal shall consist of a downward movement of the arm and the audible command', []],
  ['§4.1.2', ['agacho', 'comandos-ipf', 'setup'],
    'o árbitro só dá o sinal quando o atleta está imóvel, ereto e com os joelhos travados',
    'When the lifter is motionless, erect (slight deviation is allowable) with knees locked the Chief Referee will give the signal to begin the lift', []],
  ['§4.1.2', ['agacho', 'comandos-ipf'],
    'se depois de cinco segundos o atleta não estiver na posição correta para iniciar, o árbitro manda recolocar a barra',
    'the lifter will be requested to "Replace" the bar, together with a backward movement of the arm, if after a period of five seconds he is not in the correct position to begin the lift',
    [{ name: 'espera_maxima_setup', value: 5, unit: 'seg', frame: 'seg' }]],
  ['§4.1.2', ['agacho', 'setup', 'comandos-ipf'],
    'antes de receber o sinal, o atleta pode fazer qualquer ajuste de posição permitido pelas regras, sem penalidade',
    'Before receiving the signal to "squat" the lifter may make any position adjustments within the rules, without penalty', []],
  ['§4.1.4', ['agacho', 'tecnica'],
    'o atleta tem que subir por vontade própria até a posição ereta com os joelhos travados',
    'The lifter must recover at will to an upright position with the knees locked', []],
  ['§4.1.4', ['agacho', 'comandos-ipf'],
    'o sinal para recolocar a barra só vem quando o atleta está imóvel na posição final aparente',
    'When the lifter is motionless (in the apparent final position) the Chief Referee will give the signal to rack the bar', []],
  ['§4.1.5', ['agacho', 'comandos-ipf'],
    'o sinal de encerramento é um movimento do braço para trás mais o comando audível rack',
    'The signal to rack the bar will consist of a backward motion of the arm and the audible command', []],
  ['§4.1.5', ['agacho', 'comandos-ipf', 'erro-comum'],
    'movimento de pés depois do sinal de rack não é causa de anulação',
    'Foot movement after the rack signal will not be cause for failure', []],
  ['§4.1.5', ['agacho', 'erro-comum'],
    'o atleta não pode sair andando pela frente do rack depois de completar o levantamento',
    'The lifter is not allowed to walk out through the front of the rack after completion of the lift', []],
  ['§4.1.1', ['agacho', 'setup', 'equipamento'],
    'a barra fica na horizontal sobre os ombros, a uma altura não mais baixa que o nível do deltoide posterior',
    'with the barbell placed horizontally across the shoulders, at a height no lower than the posterior deltoid level', []],
  ['§4.1.1', ['agacho', 'pegada'],
    'mãos, polegares e dedos têm que ficar em contato completo com a barra durante todo o levantamento, mas o polegar não precisa envolver a barra',
    'The thumbs are not required to wrap around the bar', []],
  ['§4.1.1', ['agacho', 'pegada'],
    'as mãos podem ficar em qualquer ponto da barra desde que dentro das presilhas internas ou em contato com elas',
    'The hands may be positioned anywhere on the bar inside and or in contact with the inner collars', []],

  // ---------- AGACHAMENTO: causas de anulação ----------
  ['§4.1.1.1', ['agacho', 'comandos-ipf', 'erro-comum'],
    'anula o agachamento: não observar os sinais do árbitro central no início ou no fim do levantamento',
    'Failure to observe the Chief Referee’s signals at the commencement or completion of a lift', []],
  ['§4.1.1.2', ['agacho', 'erro-comum'],
    'anula o agachamento: duplo quique no fundo do movimento, ou qualquer movimento descendente durante a subida',
    'Double bouncing at the bottom of the lift, or any downward movement during the ascent', []],
  ['§4.1.1.3', ['agacho', 'erro-comum'],
    'anula o agachamento: não assumir posição ereta com os joelhos travados no início ou no fim',
    'Failure to assume an upright position with the knees locked at the commencement or completion of the lift', []],
  ['§4.1.1.4', ['agacho', 'erro-comum'],
    'anula o agachamento: dar um passo para trás ou para a frente, ou mover os pés lateralmente; rolar o pé entre a ponta e o calcanhar é permitido',
    'Stepping backward or forward or moving the feet laterally. Rocking the feet between the ball and heel is permitted', []],
  ['§4.1.1.5', ['agacho', 'profundidade', 'erro-comum'],
    'anula o agachamento: não dobrar os joelhos e baixar o corpo até a superfície superior das pernas na articulação do quadril ficar mais baixa que o topo dos joelhos',
    'Failure to bend the knees and lower the body until the top surface of the legs at the hip joint is lower than the top of the knees, as in the diagram', []],
  ['§4.1.1.6', ['agacho', 'erro-comum'],
    'anula o agachamento: contato do spotter com a barra ou com o atleta entre os sinais do árbitro, para facilitar o levantamento',
    'Contact with the bar or the lifter by the spotter/loaders between the Chief Referee’s signals in order to make the lift easier', []],
  ['§4.1.1.7', ['agacho', 'erro-comum', 'tecnica'],
    'anula o agachamento: contato dos cotovelos ou braços com as pernas; contato leve é permitido se não houver apoio que ajude o atleta',
    'Contact of the elbows or upper arms with the legs. Slight contact is permitted if there is no supporting that might aid the lifter', []],
  ['§4.1.1.8', ['agacho', 'erro-comum'],
    'anula o agachamento: largar ou jogar a barra depois de completar o levantamento',
    'Any dropping or dumping of the bar after completion of the lift', []],
  ['§4.1.1.9', ['agacho', 'regras-ipf'],
    'anula o agachamento: descumprir qualquer item das regras de execução do agachamento',
    'Failure to comply with any of the items outlined under Rules of Performance for the squat', []],
  ['§2.9.RED', ['agacho', 'profundidade', 'comandos-ipf'],
    'o cartão vermelho no agachamento significa exatamente uma coisa: falta de profundidade',
    'Failure to bend the knees and lower the body until the top surface of the legs at the hip joint is lower than the top of the knees.', []],

  // ---------- SUPINO ----------
  ['§4.2.2', ['supino', 'setup'],
    'o atleta deita de costas com cabeça, ombros e glúteos em contato com a superfície do banco, e os pés planos no chão',
    'The lifter must lie on their back with the head, shoulders, and buttocks', []],
  ['§4.2.2', ['supino', 'setup'],
    'os pés têm que ficar planos no chão, tão planos quanto o formato do sapato permitir',
    'The feet must be flat on the floor (as flat as the shape of the shoe will allow)', []],
  ['§4.2.2', ['supino', 'pegada'],
    'a pegada do supino tem que ser com o polegar envolvendo a barra',
    'Hands, thumbs and fingers must completely grip the bar positioned in the rack stands with a thumb around grip', []],
  ['§4.2.2', ['supino', 'setup', 'erro-comum'],
    'durante a montagem no banco o atleta não pode apoiar os pés sobre o banco',
    'During the set-up on the bench, the athlete is not allowed to place his/her feet on the bench', []],
  ['§4.2.2', ['supino', 'setup'],
    'movimento de pé é permitido durante o supino, desde que o pé continue plano na plataforma',
    'Foot movement is permissible but must remain flat on the platform', []],
  ['§4.2.5', ['supino', 'pegada'],
    'a distância entre as mãos não pode passar de oitenta e um centímetros, medida entre os dedos indicadores',
    'The spacing of the hands shall not exceed 81 cm measured between the forefingers',
    [{ name: 'largura_maxima_pegada', value: 81, unit: 'cm', frame: 'cm' }]],
  ['§4.2.5', ['supino', 'pegada'],
    'a pegada invertida é proibida no supino',
    'The use of the reverse grip is forbidden', []],
  ['§4.2.6', ['supino', 'comandos-ipf', 'setup'],
    'depois de tirar a barra do suporte o atleta espera com os braços retos e os cotovelos travados até o sinal do árbitro',
    'the lifter shall wait with straight arms elbows locked for the Chief Referee’s signal', []],
  ['§4.2.7', ['supino', 'comandos-ipf'],
    'o sinal de início do supino é um movimento do braço para baixo mais o comando audível start',
    'The signal to begin the attempt shall consist of a downward movement of the arm together with the audible command', []],
  ['§4.2.8', ['supino', 'comandos-ipf', 'tecnica'],
    'o atleta baixa a barra até o peito ou abdômen, segura imóvel, e só então o árbitro dá o comando press',
    'the lifter must lower the bar to the chest or abdominal area', []],
  ['§4.2.8', ['supino', 'tecnica'],
    'na descida, a face inferior dos dois cotovelos tem que chegar ao nível do topo da respectiva articulação do ombro ou abaixo dele',
    'whereby the underside of both elbow joints is lowered level with or below the top surface of each respective shoulder joint', []],
  ['§4.2.8', ['supino', 'erro-comum', 'cinto'],
    'a barra não pode tocar o cinto',
    'the bar shall not touch the belt', []],
  ['§4.2.8', ['supino', 'comandos-ipf'],
    'depois do comando press o atleta empurra a barra até os braços retos com os cotovelos travados, e o comando rack só vem quando ela estiver imóvel nessa posição',
    'The lifter must then return the bar to straight arms’ length elbows locked. When held motionless in this position the audible command', []],
  ['§4.2.8', ['supino', 'comandos-ipf', 'erro-comum'],
    'se a barra for baixada até o cinto ou não tocar o peito nem o abdômen, o comando do árbitro é rack e a tentativa acaba ali',
    'If the bar is lowered to the belt or does not touch the chest or abdominal area, the Chief Referee', []],
  ['§4.2.3', ['supino', 'setup', 'equipamento'],
    'para firmar o apoio dos pés o atleta pode usar anilhas de face plana ou blocos de no máximo trinta centímetros de altura total',
    'the lifter may use flat surfaced plates, or blocks not exceeding 30 cm in total height',
    [{ name: 'altura_maxima_blocos', value: 30, unit: 'cm', frame: 'cm' }]],
  ['§4.2.6', ['supino', 'comandos-ipf'],
    'no supino também vale a regra dos cinco segundos: passado esse tempo sem posição correta, o árbitro manda recolocar a barra',
    'the lifter will be requested to "Replace" the bar, together with a backward movement of the arm, if after a period of five seconds he is not in the correct position to begin the lift',
    [{ name: 'espera_maxima_setup', value: 5, unit: 'seg', frame: 'seg' }]],

  // ---------- SUPINO: causas de anulação ----------
  ['§4.2.1.1', ['supino', 'comandos-ipf', 'erro-comum'],
    'anula o supino: não observar os sinais do árbitro central no início, durante ou no fim do levantamento',
    'Failure to observe the Chief Referee’s signals at the commencement, during or completion of the lift', []],
  ['§4.2.1.2', ['supino', 'erro-comum', 'setup'],
    'anula o supino: qualquer mudança da posição escolhida durante o levantamento, ou seja, qualquer movimento de elevação da cabeça, dos ombros ou dos glúteos, ou movimento lateral das mãos na barra',
    'Any change in the elected lifting position during the lift proper i.e. any raising movement of the head, shoulders, or buttocks, from the bench, or lateral movement of hands on the bar', []],
  ['§4.2.1.3', ['supino', 'erro-comum'],
    'anula o supino: afundar ou impulsionar a barra contra o peito depois de ela já estar imóvel, de modo a facilitar o levantamento',
    'Heaving or Sinking the bar into the chest or abdominal area after it is motionless in such a way as to make the lift easier', []],
  ['§4.2.1.4', ['supino', 'erro-comum'],
    'anula o supino: usar impulso do tronco para iniciar o movimento de subida da barra a partir do peito',
    'Utilizing upper body thrust to initiate upward movement of the bar from the chest', []],
  ['§4.2.1.5', ['supino', 'erro-comum'],
    'anula o supino: qualquer movimento descendente da barra inteira no curso do empurrão',
    'Any downward movement of the whole of the bar in the course of being pressed out', []],
  ['§4.2.1.6', ['supino', 'erro-comum', 'cinto'],
    'anula o supino: a barra não chegar ao peito ou abdômen, ou tocar o cinto',
    'Bar is not lowered to chest or abdominal area i.e. not reaching the chest or abdominal area, or the bar is touching the belt', []],
  ['§4.2.1.7', ['supino', 'erro-comum'],
    'anula o supino: não empurrar a barra até os braços retos com cotovelos travados no fim do levantamento',
    'Failure to press the bar to straight arms’ length elbows locked at the completion of the lift', []],
  ['§4.2.1.9', ['supino', 'erro-comum', 'setup'],
    'anula o supino: qualquer contato dos pés do atleta com o banco ou seus suportes; levantar os pés não é permitido',
    'Any contact of the lifter’s feet with the bench or its supports. Lifting of the feet is not allowed', []],
  ['§4.2.1.10', ['supino', 'erro-comum'],
    'anula o supino: contato deliberado entre a barra e o suporte do banco',
    'Deliberate contact between the bar and the bar rests support', []],
  ['§4.2.1.11', ['supino', 'erro-comum', 'tecnica'],
    'anula o supino: não baixar a face inferior dos dois cotovelos até o nível do topo da respectiva articulação do ombro ou abaixo dele',
    'Failure to lower the underside of both elbow joints level with or below the top surface of each respective shoulder joint', []],
  ['§4.2.1.8', ['supino', 'erro-comum'],
    'anula o supino: contato do spotter com a barra ou com o atleta entre os sinais do árbitro, para facilitar o levantamento',
    'Contact with the bar or the lifter by the spotter/loaders between the Chief Referee’s signals, in order to make the lift easier', []],
  ['§4.2.1.12', ['supino', 'regras-ipf'],
    'anula o supino: descumprir qualquer item das regras de execução',
    'Failure to comply with any of the items outlined under the Rules of Performance', []],

  // ---------- TERRA ----------
  ['§4.3.1', ['terra', 'pegada', 'setup'],
    'no terra a pegada é livre, com as duas mãos, e a barra é levantada até o atleta ficar de pé ereto',
    'gripped with an optional grip in both hands and lifted until the lifter is standing erect', []],
  ['§4.3.2', ['terra', 'tecnica'],
    'no fim do terra os joelhos têm que estar travados em posição reta',
    'On completion of the lift the knees shall be locked in a straight position', []],
  ['§4.3.2', ['terra', 'tecnica'],
    'o feixe anterior do deltoide tem que ficar atrás da projeção imaginária da barra',
    'The front bundle of the deltoid muscle should be placed behind the imaginary projection of the bar', []],
  ['§4.3.3', ['terra', 'comandos-ipf'],
    'o sinal do terra é um movimento do braço para baixo mais o comando audível down, e ele só vem quando a barra está imóvel e o atleta na posição final aparente',
    'The signal will not be given until the bar is held motionless and the lifter is in the apparent finished position', []],
  ['§4.3.4', ['terra', 'regras-ipf'],
    'qualquer subida da barra ou qualquer tentativa deliberada de subi-la já conta como tentativa',
    'Any rising of the bar or any deliberate attempt to do so will count as an attempt', []],
  ['§4.3.4', ['terra', 'tecnica'],
    'iniciada a tentativa, nenhum movimento descendente é permitido até o atleta alcançar a posição ereta com os joelhos travados',
    'Once the attempt has begun no downward movement is allowed until the lifter reaches the erect position with the knees locked', []],
  ['§4.3.4', ['terra', 'tecnica'],
    'se a barra assenta um pouco quando os ombros vão para trás no fim do movimento, isso não é motivo para anular',
    'If the bar settles as the shoulders come back (slightly downward on completion) this should not be reason to disqualify the lift', []],
  ['§7.3', ['terra', 'comandos-ipf'],
    'no terra não existe sinal de início: o atleta puxa quando quiser',
    'No signal required', []],

  // ---------- TERRA: causas de anulação ----------
  ['§4.3.1.1', ['terra', 'erro-comum'],
    'anula o terra: qualquer movimento descendente da barra antes de ela alcançar a posição final',
    'Any downward movement of the bar before it reaches the final position', []],
  ['§4.3.1.2', ['terra', 'erro-comum'],
    'anula o terra: não ficar de pé ereto com os ombros para trás',
    'Failure to stand erect with the shoulders back', []],
  ['§4.3.1.3', ['terra', 'erro-comum'],
    'anula o terra: não travar os joelhos retos no fim do levantamento',
    'Failure to lock the knees straight at the completion of the lift', []],
  ['§4.3.1.4', ['terra', 'erro-comum', 'tecnica'],
    'anula o terra: apoiar a barra nas coxas durante a execução; se a barra sobe raspando a coxa mas não é apoiada, isso não anula',
    'Supporting the bar on the thighs during the performance of the lift. If the bar edges up the thigh but is not supported this is not a reason for disqualification', []],
  ['§4.3.1.4', ['terra', 'regras-ipf'],
    'em toda decisão duvidosa do árbitro, o atleta deve ser beneficiado',
    'The lifter should benefit in all decisions of doubt made by the referee', []],
  ['§4.3.1.5', ['terra', 'erro-comum'],
    'anula o terra: dar passo para trás ou para a frente, ou mover os pés lateralmente; movimento de pé depois do comando down não anula',
    'Foot movement after the command "Down" will not be cause for failure', []],
  ['§4.3.1.6', ['terra', 'comandos-ipf', 'erro-comum'],
    'anula o terra: baixar a barra antes de receber o sinal do árbitro central',
    'Lowering the bar before receiving the Chief Referee’s signal', []],
  ['§4.3.1.7', ['terra', 'erro-comum'],
    'anula o terra: deixar a barra voltar à plataforma sem manter o controle com as duas mãos, ou seja, soltando a barra das palmas',
    'Allowing the bar to return to the platform without maintaining control with both hands, i.e., releasing the bar from the palms of the hand', []],
  ['§4.3.1.8', ['terra', 'regras-ipf'],
    'anula o terra: descumprir qualquer item das regras de execução',
    'Failure to comply with any of the items outlined under Rules of Performance', []],

  // ---------- EQUIPAMENTO CLÁSSICO ----------
  ['§3.1.SINGLET', ['equipamento', 'competicao'],
    'no clássico o macacão obrigatório é o singlet não-suportivo, e só de fabricante da lista aprovada da IPF',
    'A singlet (non-supportive lifting suit) shall be worn in competitions which are designated as Classic/Raw', []],
  ['§3.1.SINGLET', ['equipamento'],
    'as alças do singlet têm que estar sobre os ombros em todos os movimentos, sempre',
    'The singlet straps must be worn over the lifter’s shoulders at all times in all lifts in all competitions', []],
  ['§3.1.c', ['equipamento'],
    'o singlet tem que ser feito inteiramente de tecido ou material têxtil sintético, de modo a não dar nenhum suporte ao atleta',
    'The singlet must be constructed entirely of fabric or a synthetic textile material, such that no support is given to the lifter by the singlet in the execution of any lift', []],
  ['§3.1.e', ['equipamento'],
    'a perna do singlet tem que ter no mínimo três e no máximo vinte e cinco centímetros do alto da virilha para baixo',
    'There must be legs to the singlet, extending a minimum of 3 cm and a maximum of 25 cm',
    [{ name: 'perna_singlet_min', value: 3, unit: 'cm', frame: 'cm' },
     { name: 'perna_singlet_max', value: 25, unit: 'cm', frame: 'cm' }]],
  ['§3.2', ['equipamento'],
    'camiseta por baixo do singlet é obrigatória no agachamento, no supino e no terra',
    'A t-shirt must be worn under the lifting singlet by all lifters in the Squat, Bench Press and Deadlift', []],
  ['§3.2.b', ['equipamento'],
    'a manga da camiseta tem que ser justa, terminar abaixo do deltoide e não pode chegar ao cotovelo nem passar dele; também não pode ser enrolada para cima',
    'the t-shirt must have tight fit "Form Fitting" sleeves. Those sleeves must terminate below the lifter’s deltoid and must not extend onto or below the lifter’s elbow', []],
  ['§3.3', ['equipamento'],
    'camisa de suporte só é permitida em competição equipada',
    'A supportive shirt which has been accepted onto the "Approved List of Apparel and Equipment for Use at IPF Competitions" may be worn only at competitions designated as Equipped', []],
  ['§3.4', ['equipamento'],
    'qualquer roupa íntima de suporte é ilegal em competição da IPF',
    'Any supportive undergarment is not legal for use in IPF competition', []],
  ['§3.5.d', ['equipamento', 'terra'],
    'meia de cano até a canela é obrigatória no terra, para cobrir e proteger as canelas',
    'Shin length socks must be worn to cover and protect the shins while performing the deadlift', []],
  ['§3.5.c', ['equipamento'],
    'meia-calça, legging e meia de perna inteira são estritamente proibidas',
    'Full length leg stockings, tights or hose are strictly forbidden', []],
  ['§3.6', ['cinto', 'equipamento'],
    'o cinto é opcional, mas se usado tem que ficar por fora do macacão e ser de fabricante da lista aprovada',
    'Competitors may wear a belt. If worn, it shall be on the outside of the lifting suit', []],
  ['§3.6.b', ['cinto', 'equipamento'],
    'o cinto não pode ter acolchoamento, reforço ou suporte adicional de nenhum material, nem na superfície nem escondido dentro das laminações',
    'It shall not have additional padding, bracing or supports of any material either on the surface or concealed within the laminations of the belt', []],
  ['§3.6.DIM', ['cinto', 'equipamento'],
    'a largura máxima do cinto é dez centímetros',
    'Width of belt maximum 10 cm',
    [{ name: 'largura_max_cinto', value: 10, unit: 'cm', frame: 'cm' }]],
  ['§3.6.DIM', ['cinto', 'equipamento'],
    'a espessura máxima do cinto é treze milímetros ao longo do comprimento principal',
    'Thickness of belt maximum 13 mm along the main length',
    [{ name: 'espessura_max_cinto', value: 13, unit: 'mm', frame: 'mm' }]],
  ['§3.7', ['sapato', 'equipamento'],
    'usar calçado é obrigatório',
    'Shoes or boots shall be worn', []],
  ['§3.7.a', ['sapato', 'equipamento'],
    'o calçado permitido é tênis de esporte indoor, bota de levantamento de peso ou sapatilha de terra; bota de trilha não entra nessa categoria',
    'Shoes shall be taken to include only indoor sports shoes/sports boots; Weightlifting/Powerlifting boots or Deadlift slippers', []],
  ['§3.7.b', ['sapato', 'equipamento'],
    'a espessura da sola não pode passar de cinco centímetros em nenhum ponto',
    'The sole thickness shall not exceed 5 cm at any point',
    [{ name: 'espessura_max_sola', value: 5, unit: 'cm', frame: 'cm' }]],
  ['§3.7.f', ['sapato', 'equipamento'],
    'o calçado tem que estar devidamente fechado, com cadarço amarrado ou velcro preso, quando o atleta está na plataforma',
    'Shoes must be properly fastened (laces tied or velcro straps secured) when the lifter is on the platform', []],
  ['§3.8', ['equipamento', 'agacho'],
    'joelheira só pode ser cilindro de neoprene, só no joelho, e nunca junto com faixa de joelho',
    'Knee sleeves cannot be worn where the lifter also wears knee wraps', []],
  ['§3.8.b', ['equipamento'],
    'a joelheira tem espessura máxima de sete milímetros e comprimento máximo de trinta centímetros',
    'Knee sleeves shall be of a maximum thickness of 7 mm and a maximum length of 30 cm',
    [{ name: 'espessura_max_joelheira', value: 7, unit: 'mm', frame: 'mm' },
     { name: 'comprimento_max_joelheira', value: 30, unit: 'cm', frame: 'cm' }]],
  ['§3.8.c', ['equipamento'],
    'a joelheira não pode ter tira, velcro, cordão, acolchoamento ou dispositivo de suporte, e tem que ser cilindro contínuo sem furos',
    'Knee sleeves shall not have any additional strapping, Velcro, drawstrings, padding or similar supportive devices in or on them', []],
  ['§3.8.d', ['equipamento'],
    'na plataforma a joelheira não pode encostar no macacão nem na meia, e tem que estar centrada sobre a articulação do joelho',
    'knee sleeves must not be in contact with the lifter’s suit (other than long-legged) or socks and must be centered over the knee joint', []],
  ['§3.8.e', ['equipamento'],
    'o atleta pode receber ajuda de outra pessoa para vestir a joelheira',
    'Athletes are permitted to receive personal assistance in the application of their knee sleeves', []],
  ['§3.9.KNEE', ['equipamento', 'faixa'],
    'faixa de joelho só é permitida em competição equipada, e a combinação de faixa com joelheira é estritamente proibida',
    'A combination of the two is strictly forbidden', []],
  ['§3.9.WRIST', ['faixa', 'equipamento'],
    'a faixa de punho não pode passar de um metro de comprimento nem de oito centímetros de largura, e o velcro e as alças de fechamento contam dentro desse metro',
    'Wrists wraps shall not exceed 1 m in length and 8 cm in width. Any sleeves and Velcro patches/tabs for securing must be incorporated within the one-meter length',
    [{ name: 'comprimento_max_faixa_punho', value: 1, unit: 'm', frame: 'm' },
     { name: 'largura_max_faixa_punho', value: 8, unit: 'cm', frame: 'cm' }]],
  ['§3.9.WRIST', ['faixa', 'equipamento'],
    'a cobertura do punho não pode passar de dez centímetros acima e dois centímetros abaixo do centro da articulação, nem exceder doze centímetros de largura coberta',
    'A wrist covering shall not extend beyond 10 cm above and 2 cm below the center of the wrist joint and shall not exceed a covering width of 12 cm',
    [{ name: 'faixa_punho_acima', value: 10, unit: 'cm', frame: 'cm' },
     { name: 'faixa_punho_abaixo', value: 2, unit: 'cm', frame: 'cm' },
     { name: 'faixa_punho_largura_coberta', value: 12, unit: 'cm', frame: 'cm' }]],
  ['§3.9.WRIST', ['faixa', 'equipamento'],
    'a alça da faixa de punho não pode continuar sobre o polegar ou os dedos durante o levantamento',
    'The loop shall not remain over the thumb or fingers during the actual lift', []],
  ['§3.10', ['equipamento'],
    'boné e qualquer chapéu são estritamente proibidos na plataforma durante o levantamento',
    'Hats are strictly forbidden to be worn on the platform during lifting', []],
  ['§3.10', ['equipamento', 'faixa'],
    'a combinação de faixa de punho com munhequeira de suor não é permitida',
    'A combination of wrist wraps and sweat bands is not allowed', []],
  ['§3.11', ['equipamento', 'pegada'],
    'são permitidas duas camadas de fita médica em volta dos polegares, e a fita não pode ser usada como ajuda para segurar a barra',
    'Two layers of medical tape may be worn around the thumbs',
    [{ name: 'camadas_fita_polegar', value: 2, unit: 'camadas', frame: 'contagem' }]],
  ['§3.14.a', ['equipamento'],
    'óleo, graxa e qualquer lubrificante no corpo ou no equipamento são estritamente proibidos',
    'The use of oil, grease or other lubricants on the body, or personal equipment is strictly forbidden', []],
  ['§3.14.b', ['equipamento'],
    'talco, pó, resina e carbonato de magnésio são as únicas substâncias que podem ser aplicadas ao corpo e à roupa, e nunca nas faixas',
    'Baby powder, resin, talc or magnesium carbonates are the only substances that may be added to the body and attire, but not to the wraps', []],
  ['§3.14.c', ['sapato', 'equipamento'],
    'qualquer forma de adesivo na sola do calçado é estritamente proibida, incluindo lixa e resina; borrifar água é aceitável',
    'The use of any form of adhesive on the underside of footwear is strictly forbidden', []],
  ['§3.12.a', ['equipamento', 'competicao'],
    'a inspeção de equipamento pessoal pode acontecer a qualquer momento do evento, até no máximo trinta minutos antes do início da categoria do atleta',
    'may take place at any time (times may be announced at the Technical Meeting) throughout the meet prior to within thirty minutes of the start for their particular bodyweight category',
    [{ name: 'antecedencia_min_inspecao', value: 30, unit: 'min', frame: 'min' }]],
  ['§3.12.f', ['equipamento', 'competicao'],
    'se depois da inspeção o atleta aparecer na plataforma usando qualquer item ilegal, ele é imediatamente desclassificado da competição',
    'If after the inspection a lifter appears on the platform wearing or using any illegal item, other than that which may have inadvertently been passed by the referees, the lifter shall immediately be disqualified from the competition', []],
  ['§3.12.d', ['equipamento'],
    'qualquer item considerado sujo ou rasgado é rejeitado na inspeção',
    'Any item considered unclean or torn shall be rejected', []],

  // ---------- PESAGEM ----------
  ['§5.1', ['competicao', 'peso-corporal'],
    'a pesagem não pode acontecer com mais de duas horas de antecedência do início da competição da categoria',
    'Weighing in of the competitors must take place no earlier than two hours before the start of the competition',
    [{ name: 'antecedencia_max_pesagem', value: 2, unit: 'horas', frame: 'horas' }]],
  ['§5.3', ['competicao', 'peso-corporal'],
    'a janela de pesagem dura uma hora e meia',
    'The weigh in period will last one and a half hours',
    [{ name: 'duracao_janela_pesagem', value: 1.5, unit: 'horas', frame: 'horas' }]],
  ['§5.4', ['competicao', 'peso-corporal'],
    'a pesagem é feita em sala de porta fechada, com o atleta, o técnico do mesmo gênero e os árbitros designados',
    'The weigh in for each competitor will be carried out in a room with the door closed', []],
  ['§5.4', ['competicao'],
    'o atleta precisa se identificar com documento de identidade ou passaporte na pesagem',
    'Lifters need to identify himself/herself themselves with an ID/Passport', []],
  ['§5.5', ['competicao', 'peso-corporal'],
    'o atleta pode ser pesado nu ou de roupa íntima, e a roupa mínima na pesagem se limita a singlet aprovado, uma camiseta aprovada, roupa íntima padrão e nenhum calçado',
    'Minimal clothing, for purposes of weigh-in, shall be strictly limited to: (a) The approved lifting singlet. (b) One approved t-shirt (if applicable to the division); (c) Standard underwear compliant with IPF specifications; and (d) No footwear', []],
  ['§5.6', ['competicao', 'peso-corporal'],
    'cada atleta só é pesado uma vez, e só quem está fora dos limites da categoria pode voltar à balança dentro da janela',
    'Each lifter may only be weighed once. Only those whose bodyweight is heavier or lighter than the category limits of the category entered are allowed to return to the scales', []],
  ['§5.6', ['competicao', 'peso-corporal'],
    'quem não fizer o peso dentro da janela de pesagem é eliminado da competição',
    'They must return to the scales and make weight within the limits of the hour and a half allowed for the weigh in; otherwise, they will be eliminated from the competition', []],
  ['§5.7', ['competicao', 'peso-corporal'],
    'o atleta só pode pesar na categoria em que foi nomeado vinte e um dias antes da data da competição',
    'A lifter may only weigh in the category in which he was nominated 21 days prior to the meet date',
    [{ name: 'prazo_nomeacao_final', value: 21, unit: 'dias', frame: 'dias' }]],
  ['§5.8', ['competicao', 'setup'],
    'o atleta deve conferir a altura dos suportes de agachamento e supino e dos blocos de pé antes do início da competição, e a folha de altura tem que ser assinada',
    'Lifters should check squat and bench press rack heights and foot blocks prior to the start of the competition. The rack height sheet must be signed or initialed after the check by the lifter or coach', []],
  ['§6.1.a', ['competicao'],
    'na pesagem o atleta ou o técnico tem que declarar o peso de abertura dos três movimentos',
    'At the weigh in, the lifter or his coach must declare a starting weight for all three lifts',
    [{ name: 'aberturas_declaradas_na_pesagem', value: 3, unit: 'movimentos', frame: 'contagem' }]],

  // ---------- CATEGORIAS, TENTATIVAS, ARBITRAGEM ----------
  ['§1.2', ['peso-corporal', 'competicao'],
    'a categoria masculina de noventa e três quilos vai de oitenta e três vírgula zero um até noventa e três quilos de peso corporal',
    '93.0 kg Class from 83.01 kg up to 93.0 kg',
    [{ name: 'classe_93_limite', value: 93.0, unit: 'kg', frame: 'kg' },
     { name: 'classe_93_piso', value: 83.01, unit: 'kg', frame: 'kg' }]],
  ['§1.2', ['peso-corporal', 'competicao'],
    'a categoria masculina de oitenta e três quilos vai de setenta e quatro vírgula zero um até oitenta e três quilos de peso corporal',
    '83.0 kg Class from 74.01 kg up to 83.0 kg',
    [{ name: 'classe_83_limite', value: 83.0, unit: 'kg', frame: 'kg' },
     { name: 'classe_83_piso', value: 74.01, unit: 'kg', frame: 'kg' }]],
  ['§1.1.e', ['competicao'],
    'cada atleta tem três tentativas em cada movimento e a melhor tentativa válida de cada um entra no total',
    'Each competitor is allowed three attempts on each lift. The lifter’s best valid attempt on each lift counts toward his competition total',
    [{ name: 'tentativas_por_movimento', value: 3, unit: 'tentativas', frame: 'contagem' }]],
  ['§1.1.e', ['competicao', 'peso-corporal'],
    'no empate de total, o atleta mais leve fica na frente do mais pesado',
    'If two or more lifters achieve the same total, the lighter lifter ranks above the heavier lifter', []],
  ['§6.3.4', ['competicao'],
    'o peso da barra tem que ser sempre múltiplo de dois vírgula cinco quilos, e a progressão entre tentativas tem que ser de pelo menos dois vírgula cinco quilos',
    'the weight of the barbell must always be a multiple of 2.5 kg',
    [{ name: 'incremento_minimo', value: 2.5, unit: 'kg', frame: 'kg' }]],
  ['§6.3.4.a', ['competicao'],
    'numa tentativa de recorde o peso da barra tem que superar o recorde vigente em pelo menos zero vírgula cinco quilo',
    'In a record attempt the weight of the barbell must be at least 0.5 kg in excess of the current record',
    [{ name: 'margem_recorde', value: 0.5, unit: 'kg', frame: 'kg' }]],
  ['§6.1.j', ['competicao'],
    'a segunda e a terceira tentativa têm que ser declaradas em até um minuto contado a partir do momento em que as luzes acendem',
    'A lifter must submit his second and third attempts within one minute of completing his preceding attempt. The one minute will begin from the time that the lights are activated',
    [{ name: 'prazo_declaracao', value: 1, unit: 'min', frame: 'min' }]],
  ['§6.1.j', ['competicao'],
    'se nada for declarado dentro do prazo, o atleta recebe automaticamente um acréscimo de dois vírgula cinco quilos na tentativa seguinte',
    'If no weight is submitted within the one-minute time allowance, the lifter will be granted a 2.5 kg increase on his next attempt',
    [{ name: 'acrescimo_automatico', value: 2.5, unit: 'kg', frame: 'kg' }]],
  ['§6.1.i', ['competicao'],
    'é permitida uma única mudança de peso na primeira tentativa de cada movimento, para mais ou para menos',
    'A lifter is permitted one change of weight on the first attempt of each lift. The change of weight may be higher or lower than that originally submitted', []],
  ['§6.1.k', ['competicao'],
    'o peso declarado para a segunda tentativa não pode ser mudado, e a terceira tentativa de agachamento e de supino também não',
    'Weights submitted for second round attempts on all three lifts cannot be changed. Similarly, third round attempts on the squat and bench press cannot be changed', []],
  ['§6.1.l', ['competicao', 'terra'],
    'só na terceira tentativa do terra são permitidas duas mudanças de peso, desde que o atleta ainda não tenha sido chamado à barra já carregada com o peso anterior',
    'In the third round of the deadlift, two changes are permitted',
    [{ name: 'mudancas_terceira_terra', value: 2, unit: 'mudanças', frame: 'contagem' }]],
  ['§6.1.g', ['competicao'],
    'quem falha uma tentativa não repete em seguida: tem que esperar a próxima rodada para tentar aquele peso de novo',
    'If unsuccessful with an attempt, the lifter does not follow himself, but must wait until the next round before he can attempt that weight again', []],
  ['§6.3.6', ['competicao'],
    'três tentativas falhas em qualquer movimento eliminam automaticamente o atleta da competição geral',
    'Three unsuccessful attempts in any lift will automatically eliminate the lifter from the overall competition',
    [{ name: 'falhas_para_eliminacao', value: 3, unit: 'tentativas', frame: 'contagem' }]],
  ['§6.2.d', ['competicao', 'comandos-ipf'],
    'o atleta tem um minuto para iniciar a tentativa depois de ser chamado à barra pelo locutor',
    'The lifter is allowed one minute in which to start his attempt after the Speaker calls the lifter to the bar',
    [{ name: 'prazo_iniciar_tentativa', value: 1, unit: 'min', frame: 'min' }]],
  ['§6.2.d', ['competicao', 'comandos-ipf'],
    'se o atleta não iniciar dentro do prazo, o árbitro dá o comando rack e a tentativa é declarada nula e perdida',
    'The lift will be declared "no lift" and the attempt forfeited', []],
  ['§6.2.d', ['competicao', 'agacho', 'supino'],
    'no agachamento e no supino o início da tentativa coincide com o sinal de começo do árbitro central; no terra, é quando o atleta faz uma tentativa determinada de tirar a barra do chão',
    'In the squat and bench press, the start is to coincide with the Chief Referee’s commencement signal', []],
  ['§6.2.d', ['competicao', 'setup'],
    'o relógio começa a correr assim que a barra é anunciada como pronta, então conferir a altura do rack antes de ser chamado é responsabilidade do atleta',
    'it is of great importance that the lifter or his coach check the height of the squat racks prior to being called, as once the bar is announced as being ready, the clock will be started', []],
  ['§6.3.8', ['competicao'],
    'depois de completar a tentativa o atleta tem trinta segundos para deixar a plataforma',
    'On the completion of an attempt, a lifter shall leave the platform within 30 seconds',
    [{ name: 'prazo_sair_plataforma', value: 30, unit: 'seg', frame: 'seg' }]],
  ['§6.3.2', ['competicao'],
    'o atleta não pode ajustar a roupa nem usar amônia à vista do público; a única exceção é ajustar o cinto',
    'A lifter shall not wrap, adjust his costume or use ammonia within view of the public. The only exception to this rule being that he may adjust his belt', []],
  ['§2.8', ['comandos-ipf', 'competicao'],
    'cada árbitro controla uma luz branca e uma vermelha, e as luzes acendem todas juntas, nunca separadamente',
    'Each referee will control a white and a red light. The white light indicates a "good lift," and the red light indicates a "no lift."', []],
  ['§7.1', ['comandos-ipf', 'competicao'],
    'são três árbitros: o central e dois laterais',
    'The referees shall be three in number, the Chief Referee or Center Referee and two side referees',
    [{ name: 'numero_arbitros', value: 3, unit: 'árbitros', frame: 'contagem' }]],
  ['§8.1.9', ['competicao'],
    'só uma decisão de dois a um dos árbitros pode ser considerada pelo Júri, ou seja, decisão unânime não se revisa',
    'Only 2 to 1 referees’ decision can be considered by the Jury',
    [{ name: 'luzes_majoritarias', value: 2, unit: 'luzes', frame: 'contagem' },
     { name: 'luzes_minoritarias', value: 1, unit: 'luz', frame: 'contagem' }]],
  ['§7.8', ['comandos-ipf', 'setup'],
    'antes do início do agachamento e do supino os árbitros laterais levantam o braço e mantêm levantado até o atleta estar na posição correta para começar',
    'Prior to the commencement of the Squat and Bench press the side referees will raise their arms and keep them raised until the lifter is in the correct position to begin the lift', []],
  ['§7.8', ['comandos-ipf', 'erro-comum'],
    'depois que o levantamento começa, os árbitros laterais não chamam atenção para faltas durante a execução',
    'Once a lift has commenced, the side referees will not call attention to faults during the execution of the lift', []],
  ['§7.4', ['comandos-ipf'],
    'as luzes só são acionadas depois que a barra volta ao suporte ou à plataforma, e só então os cartões indicam o motivo da anulação',
    'Once the bar has been replaced in the racks or on the platform at the completion of the lift, the referees will announce their decisions by means of the lights', []],
  ['§2.9', ['comandos-ipf', 'erro-comum'],
    'depois das luzes, o árbitro levanta um cartão indicando o motivo da anulação: vermelho é falha número um, azul é número dois e amarelo é número três',
    'Failure no. 1 = red card',
    [{ name: 'cartao_vermelho', value: 1, unit: 'falha', frame: 'contagem' },
     { name: 'cartao_azul', value: 2, unit: 'falha', frame: 'contagem' },
     { name: 'cartao_amarelo', value: 3, unit: 'falha', frame: 'contagem' }]],
  ['§1.1.a', ['competicao'],
    'a ordem dos movimentos é sempre a mesma em toda competição sob regra IPF: agachamento, supino, terra e total',
    'The International Powerlifting Federation recognizes the following lifts which must be taken in the same sequence in all competitions conducted under IPF rules', []],
];

const lines = rows.map(([at, topic, claim, verbatim, params], i) => JSON.stringify({
  id: `F001-${String(i + 1).padStart(2, '0')}`,
  src: 'IPF-TR2026',
  at,
  tier: 'O',
  certainty: 'explicit',
  topic,
  claim,
  verbatim,
  params: params ?? [],
  source: SOURCE,
}));

writeFileSync(process.argv[2], `${lines.join('\n')}\n`);
console.log(`${lines.length} claims`);
